---
title: "figure 4 - models and plots"
author: "L. Enright"
date: "2025-06-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(glmmTMB)
library(car)
library(emmeans)
library(ggpubr)

#don't think we need these df in this script
macro_long_data <- read.csv(here::here("data_le", "macro_long_data.csv"), stringsAsFactors = F) 
diversity_stability_synchrony <- read.csv(here::here("data_le", "full_plot_level_dss.csv"), stringsAsFactors = F) 
diversity_stability_synchrony_site <- read.csv(here::here("data_le", "diversity_stability_synchrony_site.csv"), stringsAsFactors = F) 
mean_plot_level_dss <- read.csv(here::here("data_le", "mean_plot_level_dss.csv"), stringsAsFactors = F) 
taxo <- read.csv(here::here("data_le", "MCR_Algal_Functional_Groups_02042025_updatedtax.csv"), stringsAsFactors = F)

# DO NEED THIS ONE
spatial_synchrony <- read.csv(here::here("data_le", "spatial_synchrony.csv"), stringsAsFactors = F) 

```

```{r}
source("R/functions.R")
```



```{r plotting standards set here}

habitat_colours <- c("Fringing" = "#D81B60",
                     "Backreef" = "#FFC107",
                     "Forereef 10m" = "#1E88E5",
                     "Forereef 17m" = "#004D40")

trends_theme <- theme_bw() + 
  theme(axis.title.x = element_text(size=24), 
        axis.text.x = element_text(size = 22, angle = 45, hjust = 1),
        axis.title.y = element_text(size=24), 
        axis.text.y = element_text(size = 22),
        plot.title = element_text(size = 24),
        panel.background = element_rect(fill = "white"), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_rect(fill = "white"),
        legend.text = element_text(size=24),
        legend.title = element_blank(),
        legend.position = 'bottom', # move legend to bottom,
        legend.key.size = unit(2, 'cm'), # increase legend size
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black")) 

model_themes <-   theme_bw() + 
  theme(axis.title.x = element_text(size=24), 
        axis.title.y = element_text(size=24), 
        axis.text.x = element_text(size=22), 
        axis.text.y = element_text(size=22),
        legend.text = element_text(size=24),
        plot.title = element_text(size=26), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_rect(fill = "white"),
        legend.title = element_blank(),
        legend.key.size = unit(2, 'cm'), # increase legend size
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend


```

```{r}
dss_spatial_ranges <- extract_ranges(spatial_synchrony, "habitat", c("spatial_synchrony", "synchrony_mean", "stability_mean"))

dss_spatial_ranges$habitat <- factor(dss_spatial_ranges$habitat, levels = c("Fringing", "Backreef", "Forereef 10m", "Forereef 17m"))

#running this factor is important for contrasts estimates outputs 
spatial_synchrony$habitat <- factor(spatial_synchrony$habitat, levels = c("Fringing", "Backreef", "Forereef 10m", "Forereef 17m"))

```
### Figure 4A - plot level stability X site level stability 

```{r alpha gamma stability mod plot}
figure4Amodel_alpha_gamma <- glmmTMB(cover_stability ~ stability_mean*habitat, family = Gamma("log"), data = spatial_synchrony)
summary(figure4Amodel_alpha_gamma)
Anova(figure4Amodel_alpha_gamma)
#slightly different than what Noam got? 
#NOAM
#                          Chisq Df Pr(>Chisq)    
# stability_mean         61.2742  1  4.965e-15 ***
# habitat                12.9328  3   0.004784 ** 
# stability_mean:habitat  9.4834  3   0.023508 * 

#ME:
#                         Chisq Df Pr(>Chisq)    
#stability_mean         61.2725  1   4.97e-15 ***
#habitat                12.9323  3   0.004785 ** 
#stability_mean:habitat  9.4832  3   0.023511 * 

performance::r2(figure4Amodel_alpha_gamma) # 0.838 #nice, matches w/ Noam

emtrends(figure4Amodel_alpha_gamma, pairwise ~ habitat, var = "stability_mean") # backreef different from fringe and forereef 10
# $contrasts
#  contrast                    estimate    SE  df z.ratio p.value
#  Fringing - Backreef            1.078 0.381 Inf   2.828  0.0242
#  Fringing - Forereef 10m        0.175 0.345 Inf   0.509  0.9571
#  Fringing - Forereef 17m        0.380 0.305 Inf   1.248  0.5965
#  Backreef - Forereef 10m       -0.903 0.349 Inf  -2.589  0.0474
#  Backreef - Forereef 17m       -0.698 0.309 Inf  -2.256  0.1085
#  Forereef 10m - Forereef 17m    0.205 0.263 Inf   0.779  0.8639
#nice, this matches w/ Noam
```

```{r plot site level stability X site level stability - Figure 4A}
alpha_gamma_figure4A_emm <- emmip(figure4Amodel_alpha_gamma,
                        habitat ~ stability_mean,
                        at = list(stability_mean = seq(0,10,0.01)), plotit = F, CIs = T)  

filtered_ag_effects <- filter_ranges(alpha_gamma_figure4A_emm, dss_spatial_ranges, "habitat", "stability_mean")


(alpha_gamma_stability_plot_figure4A <- 
  ggplot() +
  geom_point(data = spatial_synchrony,
             aes(x = stability_mean, y = cover_stability, colour = habitat), size = 1, alpha = 0.5) + 
  geom_line(data = filtered_ag_effects, aes(x = stability_mean, y = exp(yvar), colour = habitat), size = 1.5) +
  geom_ribbon(data = filtered_ag_effects, aes(x = stability_mean, ymin = exp(LCL), ymax = exp(UCL), fill = habitat),
              alpha = 0.3) +
  scale_colour_manual(values = habitat_colours) +
  scale_fill_manual(values = habitat_colours) +
  labs(y = "Site-Level Stability", x = "Mean Plot-Level Stability", title = "") +
  scale_y_continuous(limits = c(0.5, 4.2), breaks = c(1,2,3,4)) +
  model_themes
         )

#what is wrong with error ribbon for forereef 17 m?
```


### Figure 4B - spatial sychrony X site level stability 
```{r model site level stability X spatial synchrony - Figure 4B}
spatial_synchrony_mod_Fig4B <- glmmTMB(cover_stability ~ spatial_synchrony*habitat, family = Gamma("log"), data = spatial_synchrony)
hist(residuals(spatial_synchrony_mod_Fig4B)) # a little skew
plot(residuals(spatial_synchrony_mod_Fig4B) ~ predict(spatial_synchrony_mod_Fig4B))
summary(spatial_synchrony_mod_Fig4B)
car::Anova(spatial_synchrony_mod_Fig4B)
#I got slightly different than Noam's version on Github
#ME:
#                            Chisq Df Pr(>Chisq)    
#spatial_synchrony         16.2914  1  5.431e-05 ***
#habitat                   19.5303  3  0.0002124 ***
#spatial_synchrony:habitat  6.7239  3  0.0812369 . 

#NOAM:
#                             Chisq Df Pr(>Chisq)    
# spatial_synchrony         16.2942  1  5.423e-05 ***
# habitat                   19.5302  3  0.0002124 ***
# spatial_synchrony:habitat  6.7253  3  0.0811882 .  

performance::r2(spatial_synchrony_mod_Fig4B) # Noam = 0.64; Me: Nagelkerke's R2: 0.638 (matches)

emtrends(spatial_synchrony_mod_Fig4B, pairwise ~ habitat, var = "spatial_synchrony")
#NOAM OUTPUT
# no sig differences but close
# contrast                    estimate    SE  df z.ratio p.value
# Fringing - Backreef            0.404 1.764 Inf   0.229  0.9958
# Fringing - Forereef 10m        1.365 1.754 Inf   0.778  0.8643
# Fringing - Forereef 17m        3.112 1.882 Inf   1.654  0.3484
# Backreef - Forereef 10m        0.961 0.857 Inf   1.121  0.6766
# Backreef - Forereef 17m        2.708 1.095 Inf   2.472  0.0643
# Forereef 10m - Forereef 17m    1.747 1.078 Inf   1.621  0.3667



```

```{r plot site level stability X spatial synchrony - Figure 4B}
spat_stab_emm <- emmip(spatial_synchrony_mod_Fig4B,
                        habitat ~ spatial_synchrony,
                        at = list(spatial_synchrony = seq(0,1,0.01)), plotit = F, CIs = T)  

filtered_spat_stab_effects <- filter_ranges(spat_stab_emm, dss_spatial_ranges, "habitat", "spatial_synchrony")


(spatial_synchrony_plot_figure4b <- 
  ggplot() +
  geom_point(data = spatial_synchrony,
             aes(x = spatial_synchrony, y = cover_stability, colour = habitat), size = 1, alpha = 0.5) + 
  geom_line(data = filtered_spat_stab_effects, aes(x = spatial_synchrony, y = exp(yvar), colour = habitat), size = 1.5) +
  geom_ribbon(data = filtered_spat_stab_effects, aes(x = spatial_synchrony, ymin = exp(LCL), ymax = exp(UCL), fill = habitat),
              alpha = 0.3) +
  scale_colour_manual(values = habitat_colours) +
  scale_fill_manual(values = habitat_colours) +
  labs(y = "Site-Level Stability", x = "Spatial Synchrony", title = "", y = "Site Level Stability") +
  scale_y_continuous(limits = c(0.5, 4.2), breaks = c(1,2,3,4)) +
  model_themes
         )

```


### Figure 4C - Ratio

```{r Figure 4C - Ratio} 
#spatial_synchrony dataframe has average plot level stability AND site level stability columns, so using this one. 

#add stability ratio 
# site / plot 
# Values > 1 indicate that the site is more stable than individual plots — very intuitive.
#cover_stability = SITE LEVEL
#stability_mean = MEAN PLOT LEVEL 

figure4c_df<- spatial_synchrony %>%
  mutate(ratio = cover_stability/stability_mean)


# plot / site
# values < 1 suggest that the site is more stable than individual plots → indicative of a portfolio effect or spatial insurance.
#another option, but NOT USING


#shape for site
figure4c_df %>%
  ggplot(aes(x = spatial_synchrony, y = ratio, color = habitat, shape = site)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE, aes(group = habitat)) +
  scale_colour_manual(values = habitat_colours) +
  labs(y = "Ratio", x = "Spatial Synchrony", title = "") +
  trends_theme #this was set at beginning of script
 # geom_abline(slope = -1, intercept = 0, linetype = "dashed", color = "red")

#no shape for site, probably using this one. 
figure4c <- figure4c_df %>%
  ggplot(aes(x = spatial_synchrony, y = ratio, color = habitat)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE, aes(group = habitat, fill = habitat), alpha = 0.3) +
#  geom_ribbon(data = filtered_spat_stab_effects, aes(x = spatial_synchrony, ymin = exp(LCL), ymax = exp(UCL), fill = habitat),
            #  alpha = 0.3) +
  scale_colour_manual(values = habitat_colours) +
  scale_fill_manual(values = habitat_colours) +
  labs(y = "Ratio", x = "Spatial Synchrony", title = "") +
  trends_theme  #this was set at beginning of script

```

```{r figure 4 panel, fig.height = 10, fig.width=18}
(figure_4 <- ggarrange(alpha_gamma_stability_plot_figure4A, spatial_synchrony_plot_figure4b, figure4c, 
                      ncol = 3, nrow = 1, 
                      common.legend = TRUE,
                      legend = "bottom", 
                      labels = c("a.", "b.", "c."),
                      font.label = list(size = 26, color = "black", face = "plain")))

#ggsave(filename = "output/figure4_09032025.jpg", figure_4, height = 15, width = 30)
```


