---
title: "Pre working group data exploration: Julianna"
output: html_document
date: "2024-07-02"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
require(here) # relative file paths
require(tidyverse) # data wrangling
require(vegan) # community/diversity analyses
```

# Bring in the data

These are the most recent file versions done by Lauren as of July 2, 2024

```{r}
allbenthos <- read_csv(here("data", "allbenthicdata_cleaned_colnames.csv")) 
algae <- read_csv(here("data", "algaeonly_cleaned_colnames.csv"))
```

# Calculate algal diversity metrics

Make a spp matrix to use with vegan

```{r}
# matrix of just species and their relative percent covers
algae %>% 
  select(-year, -location, -site, -habitat, -site_habitat, -transect, -quadrat) -> sppMat

# metadata info that is in the same order (can re-join after)
algae %>% 
  select(year, location, site, habitat, site_habitat, transect, quadrat) -> sppMeta
```


```{r}
algae %>% 
  # grab the metadata info that is in the same order (can re-join after)
  select(year, location, site, habitat, site_habitat, transect, quadrat) %>% 
  mutate(Shannon = diversity(sppMat, "shannon"))
```


# Join algae and coral data

```{r}
allbenthos %>% 
  select(year, location, site, habitat, site_habitat, transect, quadrat, coral) %>% 
  full_join(algae) -> coralAlg  
```


