---
title: "noam_data_exploration_v1"
author: "Noam Altman-Kurosaki"
date: "2024-05-09"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(here)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(vegan)
library(glmmTMB)
library(car)
library(effects)
library(DHARMa)
library(stringr)
library(MuMIn)
library(codyn)
library(nlme)
library(mgcv)
library(emmeans)
library(ecofolio) # possible other method for examining portfolio effects 
```

```{r import and format data}
# starting with all data now because of 0 algae transects/quadrats
data <- read.csv(here::here("data", "allbenthicdata_cleaned_colnames.csv"), stringsAsFactors = F) 

not_algae <- c("ascidian", "bare_space", "coral", "coral_rubble", "corallimorpharia", "heteractis_sp", "millepora_platyphylla", "no_data", "sand", "sacrophyton_sp", "shell_debris", "soft_coral", "sponge", "tridacna_sp", "zooxanthellae", "row_sums")

data <- data[ , -which(names(data) %in% not_algae)]

# adding island side - adapted from Julianna's code
data <- data %>% mutate(island_side = case_when(site == "lter_1" ~ "north",
                                 site == "lter_2" ~ "north",
                                 site == "lter_3" ~ "east",
                                 site == "lter_4" ~ "east",
                                 site == "lter_5" ~ "west",
                                 site == "lter_6" ~ "west"))
data$island_side_habitat <- paste(data$island_side, data$habitat)


str(data)


meta_cols <- c(colnames(data[1:7] ), "island_side", "island_side_habitat", "stratum")
species_cols <- colnames(data)[!colnames(data) %in% meta_cols]

#pivot long 
long_data <- pivot_longer(
  data = data,
  cols = 8:77,
  names_to = "taxa",
  values_to = "percent_cover") 


 transect_level <- long_data %>%
   dplyr::group_by(year, island_side, site, habitat, transect, taxa) %>%
   dplyr::summarise(mean_cover = mean(percent_cover), 
             SE = sd(percent_cover)/sqrt(n()))
 
site_level <- long_data %>%
  dplyr::group_by(year, island_side, site, habitat, site_habitat, taxa) %>%
  dplyr::summarise(mean_site_cover = mean(percent_cover), 
            site_se = sd(percent_cover)/sqrt(n()))

```

```{r diversity indicies, fig.height = 15, fig.width=20}


wide_transect_level <- data %>%
  dplyr::group_by(year, island_side, island_side_habitat, site, habitat, site_habitat, transect) %>%
  dplyr::summarize(across(all_of(species_cols), mean, na.rm = TRUE))

alpha_diversity <-
  data.frame(
    year = as.factor(wide_transect_level$year),
    island_side = as.factor(wide_transect_level$island_side),
    island_side_habitat = as.factor(wide_transect_level$island_side_habitat),
    site = as.factor(wide_transect_level$site),
    habitat = as.factor(wide_transect_level$habitat),
    site_habitat = as.factor(wide_transect_level$site_habitat),
    transect = as.factor(wide_transect_level$transect),
    site_habitat_transect = as.factor(paste(wide_transect_level$site_habitat, wide_transect_level$transect)),
    shannon = diversity(wide_transect_level[ , -which(names(wide_transect_level) %in% meta_cols)], "shannon"),
    richness = rowSums(wide_transect_level[ , -which(names(wide_transect_level) %in% meta_cols)] > 0)
  )

alpha_diversity_means <- alpha_diversity %>%
  dplyr::group_by(year, island_side, island_side_habitat, site, habitat, site_habitat) %>%
  dplyr::summarise(richness_mean = mean(richness), 
            richness_se = sd(richness)/sqrt(n()),
            shannon_mean = mean(shannon), 
            shannon_se = sd(shannon)/sqrt(n()))

#CALLIE ADDED
#if you need to export this:
#alpha_export <- left_join(alpha_diversity, alpha_diversity_means)
#write_csv(alpha_export, here("data", "algae_alpha_diversity.csv"))

site_colours <- c("lter_1" = "cornflowerblue",
                  "lter_2" = "darkblue",
                  "lter_3" = "yellowgreen",
                  "lter_4" = "forestgreen",
                  "lter_5" = "mediumorchid",
                  "lter_6" = "orange")
island_side_colours <- c("north" = "darkblue",
                         "east" = "mediumorchid",
                         "west" = "orange")
habitat_linetypes <- c("fringing" = "solid",
                       "backreef" = "longdash",
                       "outer_10" = "twodash",
                       "outer_17" = "dotted")
habitat_shapes <- c("fringing" = 16,
                     "backreef" = 17,
                     "outer_10" = 1,
                     "outer_17" = 2)

(richness_plot <-
  ggplot(data = alpha_diversity_means) +
  geom_point(aes(x = year, y = richness_mean, colour = island_side, shape = habitat, group = island_side_habitat), size = 8) +
  geom_line(aes(x = year, y = richness_mean, colour = island_side, group = island_side_habitat), size = 1.2) +
  geom_errorbar(aes(x = year, ymin = richness_mean - richness_se , ymax = richness_mean + richness_se, colour = island_side,
                    group = island_side_habitat), width = 0.5, size = 1.2) +
  scale_colour_manual(values = island_side_colours) +
  scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~habitat)+
  labs(title = "a. richness\n", y = "richness\n") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(color = "grey20", size = 32, vjust = 0, face = "plain"),
        axis.line.y = element_line(colour = "black"),
        axis.text.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.line.x = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 28, angle = 90, vjust = 0.5, hjust=1, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(size = 32),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(2)), # increase legend text
        legend.title = element_text(size = rel(2.25)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal',
        legend.box.background = element_rect(colour = "black") # make legend horizontal
        )
    )
  
(shannon_plot <-
  ggplot(data = alpha_diversity_means) +
  geom_point(aes(x = year, y = shannon_mean, colour = island_side, shape = habitat, group = island_side_habitat), size = 8) +
  geom_line(aes(x = year, y = shannon_mean, colour = island_side, group = island_side_habitat), size = 1.2) +
  geom_errorbar(aes(x = year, ymin = shannon_mean - shannon_se , ymax = shannon_mean + shannon_se, colour = island_side,
                    group = island_side_habitat), width = 0.5, size = 1.2) +
  scale_colour_manual(values = island_side_colours) +
  scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~habitat)+
  labs(title = "b. shannon\n", y = "shannon\n") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(color = "grey20", size = 32, vjust = 0, face = "plain"),
        axis.line.y = element_line(colour = "black"),
        axis.text.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.line.x = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 28, angle = 90, vjust = 0.5, hjust=1, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(size = 32),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(2)), # increase legend text
        legend.title = element_text(size = rel(2.25)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal',
        legend.box.background = element_rect(colour = "black") # make legend horizontal
        )
    )


```

```{r alpha diversity panel graph, fig.height = 30, fig.width= 20}

ggarrange(richness_plot + rremove("x.text"), shannon_plot, common.legend = T,
          nrow = 2)

# seems like patterns in alpha diversity different depending on if you look at richness or shannon diversity 
```

```{r alpha diversity quadrat level, fig.height = 15, fig.width=20}
alpha_diversity_quad <-
  data.frame(
    year = as.numeric(data$year),
    location = as.factor(data$location),
    island_side = as.factor(data$island_side),
    island_side_habitat = as.factor(data$island_side_habitat),
    site = as.factor(data$site),
    habitat = as.factor(data$habitat),
    site_habitat = as.factor(data$site_habitat),
    transect = as.factor(data$transect),
    site_habitat_transect = as.factor(paste(data$site_habitat, data$transect)),
    shannon = diversity(data[ , -which(names(data) %in% meta_cols)], "shannon"),
    richness = rowSums(data[ , -which(names(data) %in% meta_cols)] > 0)
  )

alpha_diversity_quad_means <- alpha_diversity_quad %>%
  dplyr::group_by(year, island_side, island_side_habitat, site, habitat, site_habitat) %>%
  dplyr::summarise(richness_mean = mean(richness), 
            richness_se = sd(richness)/sqrt(n()),
            shannon_mean = mean(shannon), 
            shannon_se = sd(shannon)/sqrt(n()))

(richness_quad_plot <-
  ggplot(data = alpha_diversity_quad_means) +
  geom_point(aes(x = year, y = richness_mean, colour = island_side, shape = habitat, group = island_side_habitat), size = 8) +
  geom_line(aes(x = year, y = richness_mean, colour = island_side, group = island_side_habitat), size = 1.2) +
  geom_errorbar(aes(x = year, ymin = richness_mean - richness_se , ymax = richness_mean + richness_se, colour = island_side,
                    group = island_side_habitat), width = 0.5, size = 1.2) +
  scale_colour_manual(values = island_side_colours) +
  scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~habitat)+
  labs(title = "a. richness quad level\n", y = "richness\n") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(color = "grey20", size = 32, vjust = 0, face = "plain"),
        axis.line.y = element_line(colour = "black"),
        axis.text.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.line.x = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 28, angle = 90, vjust = 0.5, hjust=1, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(size = 32),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(2)), # increase legend text
        legend.title = element_text(size = rel(2.25)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal',
        legend.box.background = element_rect(colour = "black") # make legend horizontal
        )
    )
  
(shannon_quad_plot <-
  ggplot(data = alpha_diversity_quad_means) +
  geom_point(aes(x = year, y = shannon_mean, colour = island_side, shape = habitat, group = island_side_habitat), size = 8) +
  geom_line(aes(x = year, y = shannon_mean, colour = island_side, group = island_side_habitat), size = 1.2) +
  geom_errorbar(aes(x = year, ymin = shannon_mean - shannon_se , ymax = shannon_mean + shannon_se, colour = island_side,
                    group = island_side_habitat), width = 0.5, size = 1.2) +
  scale_colour_manual(values = island_side_colours) +
  scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~habitat)+
  labs(title = "b. shannon quad level\n", y = "shannon\n") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(color = "grey20", size = 32, vjust = 0, face = "plain"),
        axis.line.y = element_line(colour = "black"),
        axis.text.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.line.x = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 28, angle = 90, vjust = 0.5, hjust=1, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(size = 32),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(2)), # increase legend text
        legend.title = element_text(size = rel(2.25)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal',
        legend.box.background = element_rect(colour = "black") # make legend horizontal
        )
    )



```

```{r compare quad and transect level plots, fig.height = 30, fig.width= 40}
ggarrange(richness_plot + rremove("x.text"), richness_quad_plot + rremove("x.text"),
          shannon_plot,shannon_quad_plot,
          common.legend = T,
          nrow = 2, ncol = 2)

```

```{r gam approach}
# NOTE: Not sure where I'm going with this yet
# Idea is to look at smoother estimates for each time series to get an idea for the "shape" of the time series
# Not sure if worthwhile, might skip

# The below takes 17 years to run in and of itself
# gam_model <- gam(richness ~ s(year) + s(year, by = habitat) + 
#                  s(island_side, bs = "re") + s(transect, bs = "re") + s(location, bs = "re"),
#                  data = alpha_diversity_quad, family = poisson())



gam_columns <- c("location", "Intercept", "edf") # names of columns for dataframe
gam_coefficients <- # new dataframe name - same workflow as above
  data.frame(matrix(nrow = length(unique(alpha_diversity_quad$location)),
                    ncol = length(gam_columns))
             )
colnames(gam_coefficients) <- gam_columns # change column names to what was specified
gam_coefficients$location <- levels(alpha_diversity_quad$location) # populate location column with each quad/time series

# same workflow as *below (I did gls first originally)
for(i in 1:length(unique(alpha_diversity_quad$location)) ){ # for each  quadrat
  # create a new dataframe for the quadrat of the current iteration
  newData <- subset(alpha_diversity_quad, location == levels(alpha_diversity_quad$location)[i]) 
  
  # fit gam for current time series
  loop_mod <- gamm(richness ~ s(year), data = newData, correlation = corCAR1(form = ~ year), method = "REML", family = poisson)
  loop_sum <- summary(loop_mod$gam) # store summary data
  # populate appropriate row and column with the relevant coeffcients from gls
  gam_coefficients[i, 2] <- unname(loop_sum$p.coeff)
  gam_coefficients[i, 3] <- unname(loop_sum$edf)
  
}

hist(gam_coefficients$Intercept)
hist(gam_coefficients$edf) # generally around 1 except for an outlier
# lter_5 fringing Reef Algae transect 3 Quad 6 - a quadrat that has almost no algae the entire time series
# issues with quadrat - smaller sample = more 0s, makes modeling trickier
hist(subset(gam_coefficients, location != "lter_5 fringing Reef Algae transect 3 Quad 6")$edf)
sum(gam_coefficients$edf > 1.01) # all but 18/1200 quadrats can be fit by a smoother with edf < 1.01
# trends more straightforward than I anticipated?
# argument for just looking at mean richness and slope?
```

```{r gls approach, fig.height=10, fig.width=14}

# FRAMING: What is the general trend in algal alpha diversity over the course of the time series? Increasing, decreasing, neutral?
alpha_diversity_quad$logRich <- log(alpha_diversity_quad$richness + 1)
columns <- c("location", "Intercept", "Slope", "Phi") # names of columns for dataframe
gls_coefficients <- # new dataframe name
  data.frame(matrix(nrow = length(unique(alpha_diversity_quad$location)), # 1200 quadrats = 1200 different time series
                    ncol = length(columns)) # specified to make sure number of columns doesn't exceed what was specified
             )
colnames(gls_coefficients) <- columns # change column names to what was specified
gls_coefficients$location <- levels(alpha_diversity_quad$location) # populate location column with each quad/time series

for(i in 1:length(unique(alpha_diversity_quad$location)) ){ # for each  quadrat
  # create a new dataframe for the quadrat of the current iteration
  newData <- subset(alpha_diversity_quad, location == levels(alpha_diversity_quad$location)[i]) 
  
  # fit gls for current time series
  loop_mod <- gls(logRich ~ year, correlation =corAR1(form=~year), 
                  control=glsControl(msVerbose=T), data = newData)
  
  # populate appropriate row and column with the relevant coeffcients from gls
  gls_coefficients[i, 2] <- unname(coef(loop_mod)[1])
  gls_coefficients[i, 3] <- unname(coef(loop_mod)[2])
  gls_coefficients[i, 4] <- loop_mod[["modelStruct"]][["corStruct"]]
  
}

hist(gls_coefficients$Slope) # looks basically normal, bounded -Inf, Inf

hist(gls_coefficients$Intercept) # same with intercept - although it probably shouldn't be
hist(gls_coefficients$Phi)

# Start adding back in relevant metadata - probably a more elegant way to do this!!!
habitat_vector <- c(rep("backreef", 50), rep("fringing", 50), rep("outer_10", 50), rep("outer_17", 50))
transect_sequence <- c(rep(1,10),
                       rep(2,10),
                       rep(3,10),
                       rep(4,10),
                       rep(5,10))
extra_meta <- 
  data.frame(site = as.factor(c(rep("lter_1", 200),
                                rep("lter_2", 200),
                                rep("lter_3", 200),
                                rep("lter_4", 200),
                                rep("lter_5", 200),
                                rep("lter_6", 200)) ),
             island_side = as.factor(c(rep("north", 400),
                                     rep("east", 400),
                                     rep("west", 400))
                                     ),
             habitat = as.factor(rep(habitat_vector, 6 )),
             transect = as.factor(rep(transect_sequence, 240)),
             location = levels(alpha_diversity_quad$location) )

gls_coefficients_merged <- merge(gls_coefficients, extra_meta, by = "location")             

# slope_mod <- glmmTMB(Slope ~ habitat*site + (1|site/transect), data = gls_coefficients_merged)
# # model convergence problem
# summary(slope_mod) # pretty low variance in random effects
# plot(gls_res <- simulateResiduals(slope_mod)) # there are issues, but I can't figure out what they are...
# # I think this is due to 1200 obs in model
# hist(residuals(slope_mod))
# plot(predict(slope_mod) ~ residuals(slope_mod))
# Anova(slope_mod)
# # Response: Slope
# #                 Chisq Df Pr(>Chisq)    
# # habitat      1397.999  3  < 2.2e-16 ***
# # site           39.095  5  2.273e-07 ***
# # habitat:site 1738.155 15  < 2.2e-16 ***
# r.squaredGLMM(slope_mod) # 0.22, 0.24
# plot(allEffects(slope_mod))
# # backreef: richness increases on east and north shore, but relatively constant west side
# # Fringe: richness decreasing on east and west side, but relatvely constant on north shore
# # outer_10: richness neutral/decreasing on east side, but neutral/increasing on north and west side
# # outer_17: richness decreasing north/east side, but neutral west side
# # Worth noting trends are slight - arguable whether they are biologically meaningful
# 
# 
# 
# 
# slope_emm <- emmeans(slope_mod, ~ habitat*site) # create emmeans object
# emmeans::contrast(slope_emm, "consec", simple = "each", combine = TRUE, adjust = "bonferroni")
# # Note: not sure I want to include this
# emmeans(slope_mod, pairwise ~ site | habitat)
# 

## AT COAST-LEVEL
slope_mod <- glmmTMB(Slope ~ habitat*island_side + (1|island_side/site/transect), data = gls_coefficients_merged)
summary(slope_mod) # pretty low variance in random effects
plot(gls_res <- simulateResiduals(slope_mod)) 

hist(residuals(slope_mod))
plot(predict(slope_mod) ~ residuals(slope_mod))
Anova(slope_mod)
#                        Chisq Df Pr(>Chisq)    
# habitat             1301.246  3  < 2.2e-16 ***
# island_side           16.075  2  0.0003231 ***
# habitat:island_side  799.999  6  < 2.2e-16 ***
r.squaredGLMM(slope_mod) # 0.16, 0.18
plot(allEffects(slope_mod))
# backreef: richness increases on east and north shore, but relatively constant west side
# Fringe: richness decreasing on east and west side, but relatvely constant on north shore
# outer_10: richness neutral/decreasing on east side, but neutral/increasing on north and west side
# outer_17: richness decreasing north/east side, but neutral west side
# Worth noting trends are slight - arguable whether they are biologically meaningful




slope_emm <- emmeans(slope_mod, ~ habitat*island_side) # create emmeans object
emmeans::contrast(slope_emm, "consec", simple = "each", combine = TRUE, adjust = "bonferroni")
slope_plot_info <- plot(slope_emm, plotit = FALSE)
(emmeans_slope_graph <- 
  ggplot(data =slope_plot_info) +
  geom_point(aes(y = the.emmean, x = habitat, colour = island_side), size = 8, position = position_dodge(0.3)) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL, x = habitat, colour = island_side), width = 0.2, size = 1.5,
                position = position_dodge(0.3) )+
  geom_hline(yintercept = 0) +
  theme_classic() +
  labs(y = "Estimated maringal mean slope\n", x = "Habitat") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
#        panel.background = element_blank(),
        legend.text = element_text(size=20),
        legend.title = element_text(size=20),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        strip.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain") ) )

# Note: not sure I want to include this
emmeans(slope_mod, pairwise ~ island_side | habitat)
# north and east coast not different from each other in backreef
# east and west not different from each other in fringing
# north and west not different from each other outer 10
# no sites different from each other outer 17
slope_est <- as.data.frame(slope_emm) # create df of emmeans estimates


```


```{r gls plot, fig.height=20, fig.width=25}
# not sure how to visualize here... thinking something like Dornelas et al. 2014 Fig 2a
# I reached out to them about getting their code for this

ggplot(data = gls_coefficients_merged, aes(x = Slope)) +
  geom_histogram(bins = 40, aes(y = after_stat(ndensity))) +
  geom_density(alpha=0,aes(y = after_stat(ndensity)), size = 1.5 ) +
  geom_vline(xintercept = 0, size = 2, linetype = 2) +
  geom_ribbon(data = merge(gls_coefficients_merged, slope_est), aes(xmin = lower.CL, xmax = upper.CL, ymin = 0, ymax = Inf),
              fill = "red", alpha = 0.1)+
  geom_vline(data = slope_est, aes(xintercept = emmean), size = 2, linetype = 1, colour = "red") +
  facet_grid(island_side ~ habitat) +
  theme_classic() +
  labs(y = "Density\n") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
#        panel.background = element_blank(),
        legend.text = element_text(size=20),
        legend.title = element_text(size=20),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        strip.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain")
  )

```

```{r gls intercept, fig.height=20, fig.width=25}
intercept_mod <- glmmTMB(Intercept ~ habitat*island_side + (1|island_side/site/transect), data = gls_coefficients_merged)
summary(intercept_mod) # a lot of variance w/i transect, less so w/i site
plot(gls_int_res <- simulateResiduals(intercept_mod)) # same issues as above

hist(residuals(intercept_mod))
plot(predict(intercept_mod) ~ residuals(intercept_mod))
Anova(intercept_mod)
#                        Chisq Df Pr(>Chisq)    
# habitat             1285.762  3  < 2.2e-16 ***
# island_side           15.644  2  0.0004009 ***
# habitat:island_side  776.312  6  < 2.2e-16 ***
r.squaredGLMM(intercept_mod) # 0.16, 0.17
plot(allEffects(intercept_mod))

int_emm <- emmeans(intercept_mod, ~ habitat*island_side) # create emmeans object
#emmeans::contrast(int_emm, "consec", simple = "each", combine = TRUE, adjust = "bonferroni")

emmeans(intercept_mod, pairwise ~ island_side | habitat)
# same trends as with slope

int_est <- as.data.frame(int_emm) # create df of emmeans estimates

ggplot(data = gls_coefficients_merged, aes(x = Intercept)) +
  geom_histogram(bins = 40, aes(y = after_stat(ndensity))) +
  geom_density(alpha=0,aes(y = after_stat(ndensity)), size = 1.5 ) +
  geom_vline(xintercept = 0, size = 2, linetype = 2) +
  geom_ribbon(data = merge(gls_coefficients_merged, int_est), aes(xmin = lower.CL, xmax = upper.CL, ymin = 0, ymax = Inf),
              fill = "red", alpha = 0.1)+
  geom_vline(data = int_est, aes(xintercept = emmean), size = 2, linetype = 1, colour = "red") +
  facet_grid(island_side ~ habitat) +
  theme_classic() +
  labs(y = "Density\n") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
#        panel.background = element_blank(),
        legend.text = element_text(size=20),
        legend.title = element_text(size=20),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        strip.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain")
  )

```




```{r glmm approach, fig.height = 15, fig.width=25}
alpha_diversity_quad$year_factor <- as.factor(alpha_diversity_quad$year) # for glmmTMB ar1 structure
# Framing - is adiv generally higher in certain habitats/regions?

# richness_mod <- glmmTMB(
#   richness ~ island_side*habitat + (1 | island_side/site/transect/location) + ar1(year_factor + 0 | location),
#   family = poisson,
#   data = alpha_diversity_quad,
#   control = glmmTMBControl(optCtrl = list(iter.max = 2000, eval.max = 2000))
# ) # overspecified but going with it for now
# summary(richness_mod) # looks like strong autocorrelation, which makes sense to me
# Anova(richness_mod)
# plot(allEffects(richness_mod))

# probably the closest to what others have done:
richness_mod_2 <- glmmTMB(
  richness ~ year_factor*habitat*island_side + (1 | site/transect/location) + ar1(year_factor + 0 | location),
  family = poisson,
  data = alpha_diversity_quad,
  control = glmmTMBControl(optCtrl = list(iter.max = 2000, eval.max = 2000)), na.action = na.pass
) # overspecified but going with it for now

summary(richness_mod_2) # looks like strong autocorrelation, which makes sense to me
Anova(richness_mod_2)
plot(allEffects(richness_mod_2))
mod_emm <- emmeans(richness_mod_2, ~ habitat * island_side * year_factor) # if we want to compare habitats year to year
richness_plot_info <- plot(mod_emm, plotit = FALSE)
richness_plot_info$year_numeric <- as.numeric(levels(richness_plot_info$year_factor))
(emmeans_graph <- 
  ggplot(data =richness_plot_info) +
  geom_point(aes(y = exp(the.emmean), x = year_numeric, colour = island_side), size = 8) +
  geom_errorbar(aes(ymin = exp(asymp.LCL), ymax = exp(asymp.UCL), x = year_numeric, colour = island_side), 
                width = 0.2, size = 1.5) +
  geom_segment(aes(y = 5.2, yend = 5.2, x = 2006, xend = 2010), linewidth = 4, alpha = 0.2, colour = "grey") +
  geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 2) +
  geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 2) +
  facet_wrap(~habitat) +
  theme_classic() +
  labs(x = "Year", y = "Estimated marginal mean richness\n") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
#        panel.background = element_blank(),
        legend.text = element_text(size=20),
        legend.title = element_text(size=20),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        strip.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain") ) )
  


# top_rich_mod <- glmmTMB(richness ~ year_factor*habitat + year_factor*island_side + (1 | island_side/transect/location) + # ar1(year_factor + 0 | location),   family = poisson, data = alpha_diversity_quad, control = glmmTMBControl(optCtrl = list(iter.max = # 2000, eval.max = 2000)))
# summary(top_rich_mod)
# Anova(top_rich_mod)

# Julianna's model structure
j_rich_mod <- glmmTMB(richness ~ year + habitat + (1|site/transect),
               family = poisson,
               data = alpha_diversity_quad)
summary(j_rich_mod)
plot(allEffects(j_rich_mod))

grid <- expand_grid(year = unique(alpha_diversity_quad$year),
                       habitat = unique(alpha_diversity_quad$habitat),
                       site = unique(alpha_diversity_quad$site),
                       island_side = unique(alpha_diversity_quad$island_side),
                       transect = unique(alpha_diversity_quad$transect))
grid$Preds <- predict(j_rich_mod, newdata = grid)

grid %>% 
  # get transect means
  group_by(year, habitat, island_side) %>% 
  summarize(Pred_mean_richness = mean(Preds),
            SD_richness = sd(Preds)) %>% 
  ggplot(aes(x = year, y = Pred_mean_richness, group = habitat, color = habitat)) +
  geom_line() +
  theme_bw() +
  facet_wrap(~island_side)

# Given that this is largely looking at slopes for temporal trends in adiv, I prefer the gls
```


```{r turnover troubleshooting, fig.height = 30, fig.width=25}

transect_level$site_habitat <-  paste(transect_level$site, transect_level$habitat)
transect_level$stratum <- paste(transect_level$site, "-", transect_level$habitat, "-", transect_level$transect)

# long_data$site_habitat <-  paste(long_data$site, long_data$habitat)
# long_data$stratum <- paste(long_data$site, "-", long_data$habitat, "-", long_data$transect)

# turnover analyses break when I try to do it at the quadrat level
# checking if it's because there are quadrats that have effecively 0% algae
total_cover_per_quadrat_year <- long_data %>%
  group_by(location, year) %>%
  summarize(total_cover = sum(percent_cover), .groups = 'drop')

# Filter quadrats where the total percent cover is 0%
zero_cover_quadrats <- total_cover_per_quadrat_year %>%
  filter(total_cover == 0)

# Count the number of years each quadrat had 0% cover
zero_cover_count <- zero_cover_quadrats %>%
  group_by(location) %>%
  summarize(years_with_zero_cover = n())

# Filter quadrats that had 0% cover for multiple years
quadrats_multiple_years_zero_cover <- zero_cover_count %>%
  filter(years_with_zero_cover > 1)

length(unique(quadrats_multiple_years_zero_cover$location)) # 144/1200 quadrats have multiple years with no algal cover

# compare this to the number of transects with 0 algae cover
total_cover_per_transect_year <- transect_level %>%
  group_by(stratum, year) %>%
  summarize(total_cover = sum(mean_cover), .groups = 'drop')

# Filter quadrats where the total percent cover is 0%
zero_cover_transects <- total_cover_per_transect_year %>%
  filter(total_cover == 0)

# Count the number of years each quadrat had 0% cover
zero_cover_transect_count <- zero_cover_transects %>%
  group_by(stratum) %>%
  summarize(years_with_zero_cover = n())

# Filter quadrats that had 0% cover for multiple years
transects_multiple_years_zero_cover <- zero_cover_transect_count %>%
  filter(years_with_zero_cover > 1)

# NO transects ever have more than one year with 0 algal cover, as opposed to 144 quadrats
# Fairly certain this is why the turnover analyses are breaking

# identify quadrats missing timepoints
years <- unique(long_data$year)
quadrats <- unique(long_data$location)

# Create a dataframe with all combinations of quadrats and years
all_combinations <- expand.grid(location = quadrats, year = years)

# Identify the missing combinations by performing an anti-join with your actual data
missing_timepoints <- anti_join(all_combinations, long_data, by = c("location", "year"))

# Display the missing timepoints
print(missing_timepoints)

problem_children <- c(
                      "lter_5_fringing_reef_algae_transect_3_quad_9",
                      "lter_5_fringing_reef_algae_transect_3_quad_8",
                      "lter_5_fringing_reef_algae_transect_3_quad_6",
                      "lter_5_fringing_reef_algae_transect_3_quad_3",
                      "lter_5_fringing_reef_algae_transect_3_quad_10")

long_data_sub <- long_data[!long_data$location %in% problem_children, ] # remove problem children

data_sub <- data[!data$location %in% problem_children, ]

```

```{r total turnover, fig.height = 16, fig.width=24}
# the turnover function calculates turnover as the proportion or species that either appear or disappear between timepoints
total_turnover<-
  turnover(
  df = long_data_sub,
  time.var = "year",
  species.var = "taxa",
  abundance.var = "percent_cover",
  replicate.var = "location",
  metric = "total"
)

# get relevant metadata for turnover metrics
data_sub <- data[paste(data$year, data$location) %in% paste(total_turnover$year, total_turnover$location), ]

# check to make sure everything is the same length
# nrow(data_sub) # 17829
# nrow(total_turnover) # 17829

# extract metadata
turnover_meta <- data_sub[ ,which(names(data_sub) %in% meta_cols)]

# merge with turnover df
total_turnover <- merge(total_turnover, turnover_meta, by = c("year", "location"))
total_turnover$year_factor <- as.factor(total_turnover$year)

# turnover bounded between 0 and 1 --> beta regression
# need to transform due to presence of 0s and 1s
# Smithson verkuilen transformation for beta-regression
sv_trans = function(prop, N, s = 0.000005){
  (prop*(nrow(N) - 1) + s)/nrow(N)
  # where prop is the proportional value you're transforming, 
  # N is the sample size, which is specified by taking the number of rows/observations from a given dataframe,
  # and s is a small offset 
}

# for backtransforming logit transformed data in graph
inv_logit <- function(x){
  exp(x)/(1+exp(x))
}

total_turnover$Turnover_trans <- sv_trans(total_turnover$total, total_turnover)

# model
total_turnover_mod1 <- glmmTMB(Turnover_trans ~ year_factor*habitat*island_side +
                                 (1 | site/transect/location) + ar1(year_factor + 0 | location),
                               family = beta_family(), data = total_turnover) # convergence problem, probably overspecified
summary(total_turnover_mod1) # low temporal autocorrelation... maybe don't need ar1 term?
plot(total_turnover_res <- simulateResiduals(total_turnover_mod1)) # residuals look very weird
Anova(total_turnover_mod1) # obviously everything sig
total_turnover_emm <- emmeans(total_turnover_mod1, ~ year_factor*habitat*island_side)
total_turnover_plot_info <- plot(total_turnover_emm, plotit = F)
total_turnover_plot_info$year_numeric <- as.numeric(levels(total_turnover_plot_info$year_factor))

(total_turnover_emmeans_graph <- 
  ggplot(data =total_turnover_plot_info) +
  geom_point(aes(y = inv_logit(the.emmean), x = year_numeric, colour = island_side), size = 8) +
  geom_errorbar(aes(ymin = inv_logit(asymp.LCL), ymax = inv_logit(asymp.UCL), x = year_numeric, colour = island_side), 
                width = 0.2, size = 1.5) +
  geom_segment(aes(y = 1, yend = 1, x = 2006, xend = 2010), linewidth = 4, alpha = 0.2, colour = "grey") +
  geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 2) +
  geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 2) +
  facet_wrap(~habitat) +
  theme_classic() +
  labs(x = "Year", y = "Estimated marginal mean total turnover\n") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
#        panel.background = element_blank(),
        legend.text = element_text(size=20),
        legend.title = element_text(size=20),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        strip.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain") ) )

# plot
#total_turnover_means <-
#  total_turnover %>%
#  dplyr::group_by(year, island_side, site, habitat, site_habitat) %>%
#  dplyr::summarise(Turnover_mean = mean(total), 
#            Turnover_se = sd(total)/sqrt(n()))
#
#(turnover_plot <-
#  ggplot(data = total_turnover_means) +
#  geom_point(aes(x = year, y = Turnover_mean, colour = island_side, shape = habitat, group = island_side_habitat), size = 8, stroke = #2) +
#  geom_line(aes(x = year, y = Turnover_mean, colour = island_side, group = island_side_habitat), size = 1.2) +
#  geom_errorbar(aes(x = year, ymin = Turnover_mean - Turnover_se , ymax = Turnover_mean + Turnover_se, colour = island_side,
#                    group = island_side_habitat), width = 0.5, size = 1.2) +
#  scale_colour_manual(values = island_side_colours) +
#  scale_shape_manual(values = habitat_shapes) +
#  facet_wrap(~island_side_habitat, nrow = 6)+
#  labs(title = "a. Turnover\n", y = "Total turnover\n") +
#  theme_bw() + 
#  theme(panel.grid.major = element_blank(), 
#        panel.grid.minor = element_blank(),
#        panel.background = element_blank(),
#        plot.title = element_text(color = "grey20", size = 32, vjust = 0, face = "plain"),
#        axis.line.y = element_line(colour = "black"),
#        axis.text.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = .5, face = "plain"),
#        axis.title.y = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
#        axis.line.x = element_line(colour = "black"),
#        axis.text.x = element_text(color = "grey20", size = 28, angle = 90, vjust = 0.5, hjust=1, face = "plain"),
#        axis.title.x = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
#        strip.text.x = element_text(size = 32),
#        legend.key.size = unit(2, "cm"), # increase legend size
#        legend.text = element_text(size = rel(2)), # increase legend text
#        legend.title = element_text(size = rel(2.25)),
#        legend.position = 'bottom', # move legend to bottom
#        legend.box = 'horizontal',
#        legend.box.background = element_rect(colour = "black") # make legend horizontal
#        )
#    )
#
```

```{r appearances, fig.height = 16, fig.width=24}
# examine appearance and disappearances independently 
# refers to the proportion of species that appeared or disappeared relative to total species pool between two time points

appearance <-
  turnover(
  df = long_data_sub,
  time.var = "year",
  species.var = "taxa",
  abundance.var = "percent_cover",
  replicate.var = "location",
  metric = "appearance"
)

appearance <- merge(turnover_meta, appearance, by = c("year", "location"))
appearance$Appearance_trans <- sv_trans(appearance$appearance, appearance)
appearance$year_factor <- as.factor(appearance$year)

# model
appearance_turnover_mod1 <- glmmTMB(Appearance_trans ~ year_factor*habitat*island_side +
                                 (1 | site/transect/location) + ar1(year_factor + 0 | location),
                               family = beta_family(), data = appearance) # overspecified
summary(appearance_turnover_mod1) # low temporal autocorrelation and it's negative
plot(appearance_turnover_res <- simulateResiduals(appearance_turnover_mod1)) # similar residuals problem
Anova(appearance_turnover_mod1) # obviously everything sig

# appearance_turnover_mod2 <- glmmTMB(Appearance_trans ~ year_factor*habitat*site + (1 | site/transect/location),
#                                family = beta_family(), data = appearance)
# summary(appearance_turnover_mod2) # 
# plot(appearance_turnover_res2 <- simulateResiduals(appearance_turnover_mod2)) #
# Anova(appearance_turnover_mod2) 
# anova(appearance_turnover_mod2, appearance_turnover_mod1) # models are sig different from each other
# AICc(appearance_turnover_mod2, appearance_turnover_mod1) # first model is better but not as drastic as total

appearance_turnover_emm <- emmeans(appearance_turnover_mod1, ~ year_factor*habitat*island_side)
appearance_turnover_plot_info <- plot(appearance_turnover_emm, plotit = F)
appearance_turnover_plot_info$year_numeric <- as.numeric(levels(appearance_turnover_plot_info$year_factor))

(appearance_turnover_emmeans_graph <- 
  ggplot(data =appearance_turnover_plot_info) +
  geom_point(aes(y = inv_logit(the.emmean), x = year_numeric, colour = island_side), size = 8) +
  geom_errorbar(aes(ymin = inv_logit(asymp.LCL), ymax = inv_logit(asymp.UCL), x = year_numeric, colour = island_side), 
                width = 0.2, size = 1.5) +
  geom_segment(aes(y = 0.5, yend = 0.5, x = 2006, xend = 2010), linewidth = 4, alpha = 0.2, colour = "grey") +
  geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 2) +
  geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 2) +
  facet_wrap(~habitat) +
  theme_classic() +
  labs(x = "Year", y = "Estimated marginal mean appearance turnover\n") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
#        panel.background = element_blank(),
        legend.text = element_text(size=20),
        legend.title = element_text(size=20),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        strip.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain") ) )

plot(allEffects(appearance_turnover_mod1))

# appearance_means <-
#   appearance %>%
#   dplyr::group_by(year, site, habitat, site_habitat) %>%
#   dplyr::summarise(Appearance_mean = mean(appearance), 
#             Appearance_se = sd(appearance)/sqrt(n()))
# 
# (appearance_plot <-
#   ggplot(data = appearance_means) +
#   geom_point(aes(x = year, y = Appearance_mean, colour = site, shape = habitat, group = site_habitat), size = 8, stroke = 2) +
#   geom_line(aes(x = year, y = Appearance_mean, colour = site, group = site_habitat), size = 1.2) +
#   geom_errorbar(aes(x = year, ymin = Appearance_mean - Appearance_se , ymax = Appearance_mean + Appearance_se, colour = site,
#                     group = site_habitat), width = 0.5, size = 1.2) +
#   scale_colour_manual(values = site_colours) +
#   scale_shape_manual(values = habitat_shapes) +
#   facet_wrap(~site_habitat, nrow = 6)+
#   labs(title = "b. Appearances\n", y = "Total turnover\n") +
#   theme_bw() + 
#   theme(panel.grid.major = element_blank(), 
#         panel.grid.minor = element_blank(),
#         panel.background = element_blank(),
#         plot.title = element_text(color = "grey20", size = 32, vjust = 0, face = "plain"),
#         axis.line.y = element_line(colour = "black"),
#         axis.text.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = .5, face = "plain"),
#         axis.title.y = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
#         axis.line.x = element_line(colour = "black"),
#         axis.text.x = element_text(color = "grey20", size = 28, angle = 90, vjust = 0.5, hjust=1, face = "plain"),
#         axis.title.x = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
#         strip.text.x = element_text(size = 32),
#         legend.key.size = unit(2, "cm"), # increase legend size
#         legend.text = element_text(size = rel(2)), # increase legend text
#         legend.title = element_text(size = rel(2.25)),
#         legend.position = 'bottom', # move legend to bottom
#         legend.box = 'horizontal',
#         legend.box.background = element_rect(colour = "black") # make legend horizontal
#         )
#     )
# #
```

```{r disappearances, fig.width = 24, fig.height=16}
disappearance <-
  turnover(
  df = long_data_sub,
  time.var = "year",
  species.var = "taxa",
  abundance.var = "percent_cover",
  replicate.var = "location",
  metric = "disappearance"
)

disappearance <- merge(turnover_meta, disappearance, by = c("year", "location"))
disappearance$disappearance_trans <- sv_trans(disappearance$disappearance, disappearance)
disappearance$year_factor <- as.factor(disappearance$year)

# model
disappearance_turnover_mod1 <- glmmTMB(disappearance_trans ~ year_factor*habitat*island_side +
                                 (1 | site/transect/location) + ar1(year_factor + 0 | location),
                               family = beta_family(), data = disappearance) # overspecified
summary(disappearance_turnover_mod1) # low temporal autocorrelation and it's negative
plot(disappearance_turnover_res <- simulateResiduals(disappearance_turnover_mod1)) # similar residuals problem
Anova(disappearance_turnover_mod1) # obviously everything sig

# disappearance_turnover_mod2 <- glmmTMB(disappearance_trans ~ year_factor*habitat*site + (1 | site/transect/location),
#                                family = beta_family(), data = disappearance)
# summary(disappearance_turnover_mod2) # 
# plot(disappearance_turnover_res2 <- simulateResiduals(disappearance_turnover_mod2)) #
# Anova(disappearance_turnover_mod2) 
# anova(disappearance_turnover_mod2, disappearance_turnover_mod1) # models are sig different from each other
# AICc(disappearance_turnover_mod2, disappearance_turnover_mod1) # first model is better but not as drastic as total

disappearance_turnover_emm <- emmeans(disappearance_turnover_mod1, ~ year_factor*habitat*island_side)
disappearance_turnover_plot_info <- plot(disappearance_turnover_emm, plotit = F)
disappearance_turnover_plot_info$year_numeric <- as.numeric(levels(disappearance_turnover_plot_info$year_factor))

(disappearance_turnover_emmeans_graph <- 
  ggplot(data =disappearance_turnover_plot_info) +
  geom_point(aes(y = inv_logit(the.emmean), x = year_numeric, colour = island_side), size = 8) +
  geom_errorbar(aes(ymin = inv_logit(asymp.LCL), ymax = inv_logit(asymp.UCL), x = year_numeric, colour = island_side), 
                width = 0.2, size = 1.5) +
  geom_segment(aes(y = 0.5, yend = 0.5, x = 2006, xend = 2010), linewidth = 4, alpha = 0.2, colour = "grey") +
  geom_vline(xintercept = 2010, linetype = 2, colour = "black", size = 2) +
  geom_vline(xintercept = 2019, linetype = 2, colour = "red", size = 2) +
  facet_wrap(~habitat) +
  theme_classic() +
  labs(x = "Year", y = "Estimated marginal mean disappearance turnover\n") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
#        panel.background = element_blank(),
        legend.text = element_text(size=20),
        legend.title = element_text(size=20),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain"),
        strip.text.y = element_text(color = "grey20", size = 25, hjust = .5, vjust = 0, face = "plain") ) )

plot(allEffects(disappearance_turnover_mod1))

# disappearance_means <-
#   disappearance %>%
#   dplyr::group_by(year, site, habitat, site_habitat) %>%
#   dplyr::summarise(Disappearance_mean = mean(disappearance), 
#             Disappearance_se = sd(disappearance)/sqrt(n()))
# 
# (disappearance_plot <-
#   ggplot(data = disappearance_means) +
#   geom_point(aes(x = year, y = Disappearance_mean, colour = site, shape = habitat, group = site_habitat), size = 8, stroke = 2) +
#   geom_line(aes(x = year, y = Disappearance_mean, colour = site, group = site_habitat), size = 1.2) +
#   geom_errorbar(aes(x = year, ymin = Disappearance_mean - Disappearance_se , ymax = Disappearance_mean + Disappearance_se, colour = # site,
#                     group = site_habitat), width = 0.5, size = 1.2) +
#   scale_colour_manual(values = site_colours) +
#   scale_shape_manual(values = habitat_shapes) +
#   facet_wrap(~site_habitat, nrow = 6)+
#   labs(title = "c. Disappearance\n", y = "Total turnover\n") +
#   theme_bw() + 
#   theme(panel.grid.major = element_blank(), 
#         panel.grid.minor = element_blank(),
#         panel.background = element_blank(),
#         plot.title = element_text(color = "grey20", size = 32, vjust = 0, face = "plain"),
#         axis.line.y = element_line(colour = "black"),
#         axis.text.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = .5, face = "plain"),
#         axis.title.y = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
#         axis.line.x = element_line(colour = "black"),
#         axis.text.x = element_text(color = "grey20", size = 28, angle = 90, vjust = 0.5, hjust=1, face = "plain"),
#         axis.title.x = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
#         strip.text.x = element_text(size = 32),
#         legend.key.size = unit(2, "cm"), # increase legend size
#         legend.text = element_text(size = rel(2)), # increase legend text
#         legend.title = element_text(size = rel(2.25)),
#         legend.position = 'bottom', # move legend to bottom
#         legend.box = 'horizontal',
#         legend.box.background = element_rect(colour = "black") # make legend horizontal
#         )
#     )
```

```{r mean rank shift, fig.height = 24, fig.width=16}
# rank shift 

rank_shift<-
  rank_shift(
  df = long_data_sub,
  time.var = "year",
  species.var = "taxa",
  abundance.var = "percent_cover",
  replicate.var = "location"
)


rank_shift <- merge(turnover_meta, rank_shift, by = c("location"))




rank_shift_means <-
  rank_shift %>%
  dplyr::group_by(year, site, habitat, site_habitat) %>%
  dplyr::summarise(Rank_shift_mean = mean(MRS), 
            Rank_shift_se = sd(MRS)/sqrt(n()))
# Looks very weird - not sure what to do with this
(rank_shift_plot <-
  ggplot(data = rank_shift_means) +
  geom_point(aes(x = year, y = Rank_shift_mean, colour = site, shape = habitat, group = site_habitat), size = 8, stroke = 2) +
  geom_line(aes(x = year, y = Rank_shift_mean, colour = site, group = site_habitat), size = 1.2) +
  geom_errorbar(aes(x = year, ymin = Rank_shift_mean - Rank_shift_se , ymax = Rank_shift_mean + Rank_shift_se, colour = site,
                    group = site_habitat), width = 0.5, size = 1.2) +
  scale_colour_manual(values = site_colours) +
  scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~site_habitat, nrow = 6)+
  labs(title = "a. rank_shift\n", y = "Total rank_shift\n") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(color = "grey20", size = 32, vjust = 0, face = "plain"),
        axis.line.y = element_line(colour = "black"),
        axis.text.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.line.x = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 28, angle = 90, vjust = 0.5, hjust=1, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(size = 32),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(2)), # increase legend text
        legend.title = element_text(size = rel(2.25)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal',
        legend.box.background = element_rect(colour = "black") # make legend horizontal
        )
    )
```


```{r rate of change, fig.height=15, fig.width=15}
# rate change
long_data_sub$percent_cover_transformed <- wisconsin(long_data_sub$percent_cover) # wisconsin transform abundance data

# NOTE: the results here vary considerably if you used transformed vs untransformed data
# Looking into way to change distance matrix from Euclidiean to something else
rate_change_table_transformed<-
  rate_change(
  df = long_data_sub,
  time.var = "year",
  species.var = "taxa",
  abundance.var = "percent_cover_transformed",
  replicate.var = "location"
) # summarizes rate of change for each quadrat over the course of the time series



rate_change_table_transformed <- merge(turnover_meta, rate_change_table_transformed, by = "location")
hist(rate_change_table_transformed$rate_change)

rate_change_mod1 <- glmmTMB(rate_change ~ habitat*site + (1|habitat/site/transect), data = rate_change_table_transformed)
summary(rate_change_mod1)
plot(rc_res <- simulateResiduals(rate_change_mod1)) # some deviations, but sig likely due to large n
Anova(rate_change_mod1)
#                Chisq Df Pr(>Chisq)    
# habitat      187.988  3  < 2.2e-16 ***
# site          81.209  5  4.686e-16 ***
# habitat:site 143.638 15  < 2.2e-16 ***
plot(allEffects(rate_change_mod1))
# outer_17 has fewest differences
# lter_1 2 3 changing more than 4 5 6 at outer10
# backreef change highest at lter_1 2
# fringing highest at lter_1 2 6
emmeans(rate_change_mod1, pairwise ~ site | habitat)





# Untransformed
rate_change_table_untransformed<-
  rate_change(
  df = long_data_sub,
  time.var = "year",
  species.var = "taxa",
  abundance.var = "percent_cover",
  replicate.var = "location"
) # summarizes rate of change for each quadrat over the course of the time series



rate_change_table_untransformed <- merge(turnover_meta, rate_change_table_untransformed, by = "location")
hist(rate_change_table_untransformed$rate_change)

rate_change_mod2 <- glmmTMB(rate_change ~ habitat*site + (1|habitat/site/transect), data = rate_change_table_untransformed)
summary(rate_change_mod2)
plot(rc_res <- simulateResiduals(rate_change_mod2)) # as above
Anova(rate_change_mod2)
#                Chisq Df Pr(>Chisq)    
# habitat       39.224  3  1.556e-08 ***
# site          17.882  5   0.003098 ** 
# habitat:site 123.014 15  < 2.2e-16 ***
plot(allEffects(rate_change_mod1))
# eyeballing it
# outer_17 scarcely changing regardless of site
# Rate of change similar in backreef between sites
# big variance between sites in outer10 and fringing
# outer_10: As you go around the island, sites become increasing more "stable" over time (i.e. less shift toward dissimilarity)
# Effectively the opposite trend in fringing - more dissimilar over time as you go around the island
emmeans(rate_change_mod1, pairwise ~ site | habitat)

ggplot(data = rate_change_table_transformed) +
  geom_boxplot(aes(x = site, y = rate_change, colour = site) ) +
  geom_jitter(aes(x = site, y = rate_change, colour = site), width = 0.2) +
  facet_wrap(~habitat) +
  scale_colour_manual(values = site_colours) +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(color = "grey20", size = 32, vjust = 0, face = "plain"),
        axis.line.y = element_line(colour = "black"),
        axis.text.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.line.x = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 28, angle = 90, vjust = 0.5, hjust=1, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(size = 32),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(2)), # increase legend text
        legend.title = element_text(size = rel(2.25)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal',
        legend.box.background = element_rect(colour = "black") # make legend horizontal
        )

ggplot(data = rate_change_table_untransformed) +
  geom_boxplot(aes(x = site, y = rate_change, colour = site) ) +
  geom_jitter(aes(x = site, y = rate_change, colour = site), width = 0.2) +
  facet_wrap(~habitat) +
  scale_colour_manual(values = site_colours) +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(color = "grey20", size = 32, vjust = 0, face = "plain"),
        axis.line.y = element_line(colour = "black"),
        axis.text.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.line.x = element_line(colour = "black"),
        axis.text.x = element_text(color = "grey20", size = 28, angle = 90, vjust = 0.5, hjust=1, face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(size = 32),
        legend.key.size = unit(2, "cm"), # increase legend size
        legend.text = element_text(size = rel(2)), # increase legend text
        legend.title = element_text(size = rel(2.25)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal',
        legend.box.background = element_rect(colour = "black") # make legend horizontal
        )


```

```{r rate change vis method 2, fig.height=15, fig.width=15}
rate_change_untransformed<-
  rate_change_interval(
  df = long_data_sub,
  time.var = "year",
  species.var = "taxa",
  abundance.var = "percent_cover",
  replicate.var = "location"
)

rate_change_untransformed_distances <- merge(rate_change_untransformed, turnover_meta, by = "location")

rate_change_transformed<-
  rate_change_interval(
  df = long_data_sub,
  time.var = "year",
  species.var = "taxa",
  abundance.var = "percent_cover_transformed",
  replicate.var = "location"
)

rate_change_transformed_distances <- merge(rate_change_transformed, turnover_meta, by = "location")


 ggplot(rate_change_untransformed_distances,
        aes(x = interval, y = distance, colour = site, shape = habitat) )+
   facet_wrap(~habitat) + 
   geom_point() +
   scale_colour_manual(values = site_colours) +
   scale_linetype_manual(values = habitat_linetypes) +
   stat_smooth(method = "lm", se = T, size = 2) +
   scale_shape_manual(values = habitat_shapes) +
   labs(y = "Untransformed distance\n") +
   theme_bw() + 
   theme(panel.grid.major = element_blank(), 
         panel.grid.minor = element_blank(),
         panel.background = element_blank(),
         plot.title = element_text(color = "grey20", size = 32, vjust = 0, face = "plain"),
         axis.line.y = element_line(colour = "black"),
         axis.text.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = .5, face = "plain"),
         axis.title.y = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
         axis.line.x = element_line(colour = "black"),
         axis.text.x = element_text(color = "grey20", size = 28, angle = 90, vjust = 0.5, hjust=1, face = "plain"),
         axis.title.x = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
         strip.text.x = element_text(size = 32),
         legend.key.size = unit(2, "cm"), # increase legend size
         legend.text = element_text(size = rel(2)), # increase legend text
         legend.title = element_text(size = rel(2.25)),
         legend.position = 'bottom', # move legend to bottom
         legend.box = 'horizontal',
         legend.box.background = element_rect(colour = "black") # make legend horizontal
         ) 
 
 ggplot(rate_change_transformed_distances,
        aes(x = interval, y = distance, colour = site, shape = habitat) )+
   facet_wrap(~habitat) + 
   geom_point() +
   scale_colour_manual(values = site_colours) +
   scale_linetype_manual(values = habitat_linetypes) +
   stat_smooth(method = "lm", se = T, size = 2) +
   scale_shape_manual(values = habitat_shapes) +
   labs(y = "Transformed distance\n") +
   theme_bw() + 
   theme(panel.grid.major = element_blank(), 
         panel.grid.minor = element_blank(),
         panel.background = element_blank(),
         plot.title = element_text(color = "grey20", size = 32, vjust = 0, face = "plain"),
         axis.line.y = element_line(colour = "black"),
         axis.text.y = element_text(color = "grey20", size = 28, hjust = .5, vjust = .5, face = "plain"),
         axis.title.y = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
         axis.line.x = element_line(colour = "black"),
         axis.text.x = element_text(color = "grey20", size = 28, angle = 90, vjust = 0.5, hjust=1, face = "plain"),
         axis.title.x = element_text(color = "grey20", size = 32, hjust = .5, vjust = 0, face = "plain"),
         strip.text.x = element_text(size = 32),
         legend.key.size = unit(2, "cm"), # increase legend size
         legend.text = element_text(size = rel(2)), # increase legend text
         legend.title = element_text(size = rel(2.25)),
         legend.position = 'bottom', # move legend to bottom
         legend.box = 'horizontal',
         legend.box.background = element_rect(colour = "black") # make legend horizontal
         ) 
```

```{r multivariate change}
## Ran this for 13 hours and it didn't finish (obviously)
## Need to subset or specify questions or try remote access on more powerful computer
# multi_change_untransformed <-
#   multivariate_change(
#    df = long_data_sub,
#    time.var = "year",
#    species.var = "taxa",
#    abundance.var = "percent_cover",
#    replicate.var = "location"
#   )
#  

```

```{r transect level portfolio effect}
# using Anderson et al. 2013 definitions of portfolio effects - relevant fxns in ecofolio packages
wide_transect_level$stratum <- as.factor(paste(wide_transect_level$site, "-", wide_transect_level$habitat, "-", wide_transect_level$transect))


transect_portfolio_columns <- c("stratum", "portfolio_effect") # names of columns for dataframe
transect_level_portfolio <- 
  data.frame(matrix(nrow = length(unique(wide_transect_level$stratum)), 
                    ncol = length(transect_portfolio_columns))
             )
colnames(transect_level_portfolio) <- transect_portfolio_columns # change column 
transect_level_portfolio$stratum <- levels(wide_transect_level$stratum) # populate

for(i in 1:length(unique(unique(wide_transect_level$stratum))) ){ # for each  transect
  # create a new dataframe for current transect
  newData <- subset(wide_transect_level, stratum == levels(wide_transect_level$stratum)[i])
  current_matrix <- newData[ , -which(names(newData) %in% meta_cols)] # remove metadata columns
  if(sum(current_matrix) == 0){ # if this was a 0 algae transect
    transect_level_portfolio[i, 2] <- NA # set portfolio effects to 0
  }else{ # otherwise
    current_matrix <- current_matrix[, which(colSums(current_matrix) != 0)] # remove irrelevant algae
    
    transect_level_portfolio[i, 2] <- pe_mv(current_matrix, "loess_detrended") # calculate portfolio effects for current time series
  }
  
}


```

```{r CV, fig.height = 8, fig.width = 10}
# coefficient of variation
CV<-function(x){
  return(sd(x,na.rm=T)/mean(x,na.rm=T))
}

alpha_diversity$cover <- rowSums(wide_transect_level[ , -which(names(wide_transect_level) %in% meta_cols)])/100
alpha_diversity$stratum <- paste(alpha_diversity$site, "-", alpha_diversity$habitat, "-", alpha_diversity$transect)
lm_synchrony_transect <- codyn::synchrony(df = transect_level,
                                   time.var = "year",
                                   species.var = "taxa",
                                   abundance.var = "mean_cover",
                                   metric = "Loreau",
                                   replicate.var = "stratum") # Loreau and Mazancourt synchrony
colnames(lm_synchrony_transect) = c("stratum", "loreau_synchrony") # rename cols for merge later

# gross_synchrony_transect <- codyn::synchrony(df = transect_level,
#                                    time.var = "year",
#                                    species.var = "taxa",
#                                    abundance.var = "mean_cover",
#                                    metric = "Gross",
#                                    replicate.var = "stratum") # lots of warnings in this one - examine further later
# colnames(gross_synchrony_transect) = c("stratum", "Gross_synchrony") # rename cols for merge later

# stability_transect <- community_stability(df = transect_level,
#                                           time.var = "year",
#                                           abundance.var = "mean_cover",
#                                           replicate.var = "stratum") # using codyn measure of stability
# NOTE: codyn community_stability() is just the inverse of CV
diversity_stability <- alpha_diversity %>%
  dplyr::group_by(site, habitat, site_habitat, transect, stratum) %>%
  dplyr::summarise(richness_mean = mean(richness), 
            richness_se = sd(richness)/sqrt(n()),
            richness_cv = CV(richness),
            shannon_mean = mean(shannon), 
            shannon_se = sd(shannon)/sqrt(n()),
            shannon_cv = CV(shannon),
            shannon_stability = 1/CV(shannon), # Stability as defined by codyn and many others (including Pete in 2022 paper)
            cover_mean = mean(cover),
            cover_se = sd(cover)/sqrt(n()),
            cover_cv = CV(cover),
            cover_stability = 1/CV(cover)) # as above

diversity_stability <- merge(diversity_stability, lm_synchrony_transect, by = "stratum") # add in loreau and de Mazancourt synchrony
# diversity_stability <- merge(diversity_stability, gross_synchrony_transect, by = "stratum")
diversity_stability <- merge(diversity_stability, transect_level_portfolio, by = "stratum") # add in portfolio effects
pairs(~ cover_mean + cover_cv + cover_stability + 
        shannon_mean + shannon_cv + shannon_stability + 
        loreau_synchrony + portfolio_effect, data = diversity_stability)
```



```{r basic diversity stability plots transect level, fig.height=8, fig.width=10}
(shannon_cv_plot = 
  ggplot(data = diversity_stability) +
  geom_point(aes(x = shannon_mean, y = cover_stability, colour = site, shape = habitat), size = 8) + 
   scale_colour_manual(values = site_colours) +
  scale_shape_manual(values = habitat_shapes) +
#    stat_smooth(aes(x = shannon_mean, y = shannon_cv),method = "lm", se = T, size = 2) + 
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         )

(shannon_cv_plot_2 = 
  ggplot(data = diversity_stability) +
  geom_point(aes(x = shannon_mean, y = cover_stability, colour = site, shape = habitat), size = 8, stroke = 2) + 
   scale_colour_manual(values = site_colours) +
   scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~site) +
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         )

# maybe some heteroskedasticity?
# just eyeballing but it looks like "stability" is highest in lter_2 Fringe, which also has low diversity
# Functional form vs. portfolio effects?
# Either way looks sick as shit. Great clustering by habitat within site, and diversity trend is strong in lter_3 4 5
# LTER2 the trend is reversed
# lter_1 is mostly driven by habitat
# lter_6 potentially a wash


```

```{r variance vs mean diversity plot, fig.height = 8, fig.width = 10}
(diversity_mean_cv_plot = 
  ggplot(data = diversity_stability) +
  geom_point(aes(x = shannon_mean, y = shannon_cv, colour = site, shape = habitat), size = 8, stroke = 2) + 
   scale_colour_manual(values = site_colours) +
   scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~site) +
   
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         )
# More diverse regions are also those that fluctuate the least in their diversity

(diversity_mean_cv_plot_2 = 
  ggplot(data = diversity_stability) +
  geom_point(aes(x = shannon_mean, y = shannon_cv, colour = site, shape = habitat), size = 8, stroke = 2) + 
   scale_colour_manual(values = site_colours) +
   scale_shape_manual(values = habitat_shapes) +
    
#  facet_wrap(~site) +
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         ) # awesome relationship
```

```{r portfolio effects and synchrony transect level,  fig.height = 8, fig.width = 10}
(loreau_stability_plot = 
  ggplot(data = diversity_stability) +
  geom_point(aes(x = loreau_synchrony, y = cover_stability, colour = site, shape = habitat), size = 8, stroke = 2) + 
   scale_colour_manual(values = site_colours) +
   scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~site) +
   
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         )

# (gross_stability_plot = 
#   ggplot(data = diversity_stability) +
#   geom_point(aes(x = Gross_synchrony, y = cover_stability, colour = site, shape = habitat), size = 8, stroke = 2) + 
#    scale_colour_manual(values = site_colours) +
#    scale_shape_manual(values = habitat_shapes) +
#   facet_wrap(~site) +
#    
#   theme_bw() + 
#   theme(axis.title.x = element_text(size=18), 
#         axis.title.y = element_text(size=18), 
#         panel.background = element_blank(), 
#         panel.grid.major = element_blank(),  #remove major-grid labels
#         panel.grid.minor = element_blank(),  #remove minor-grid labels
#         plot.background = element_blank(),
#         legend.text = element_text(size = rel(1)), # increase legend text
#         legend.title = element_text(size = rel(1)),
#         legend.position = 'bottom', # move legend to bottom
#         legend.box = 'horizontal', # make legend horizontal
#         legend.box.background = element_rect(colour = "black"))  # add box around legend
#          )
# 
(portfolio_stability_plot = 
  ggplot(data = diversity_stability) +
  geom_point(aes(x = portfolio_effect, y = cover_stability, colour = site, shape = habitat), size = 8, stroke = 2) + 
   scale_colour_manual(values = site_colours) +
   scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~site) +
   
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         ) # almost a perfect line, which makes sense given that CV is a component of portfolio effects
```


```{r diversity, portfolio effects and synchrony transect level,  fig.height = 8, fig.width = 10}
(loreau_diversity_plot = 
  ggplot(data = diversity_stability) +
  geom_point(aes(x = shannon_mean, y = loreau_synchrony, colour = site, shape = habitat), size = 8, stroke = 2) + 
   scale_colour_manual(values = site_colours) +
   scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~site) +
   
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         )

# (gross_diversity_plot = 
#   ggplot(data = diversity_stability) +
#   geom_point(aes(x = shannon_mean, y = Gross_synchrony, colour = site, shape = habitat), size = 8, stroke = 2) + 
#    scale_colour_manual(values = site_colours) +
#    scale_shape_manual(values = habitat_shapes) +
#   facet_wrap(~site) +
#    
#   theme_bw() + 
#   theme(axis.title.x = element_text(size=18), 
#         axis.title.y = element_text(size=18), 
#         panel.background = element_blank(), 
#         panel.grid.major = element_blank(),  #remove major-grid labels
#         panel.grid.minor = element_blank(),  #remove minor-grid labels
#         plot.background = element_blank(),
#         legend.text = element_text(size = rel(1)), # increase legend text
#         legend.title = element_text(size = rel(1)),
#         legend.position = 'bottom', # move legend to bottom
#         legend.box = 'horizontal', # make legend horizontal
#         legend.box.background = element_rect(colour = "black"))  # add box around legend
#          )

(portfolio_diversity_plot = 
  ggplot(data = diversity_stability) +
  geom_point(aes(x = shannon_mean, y = portfolio_effect, colour = site, shape = habitat), size = 8, stroke = 2) + 
   scale_colour_manual(values = site_colours) +
   scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~site) +
   
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         )
```

```{r model selection}
diversity_mod_universal <- glmmTMB(cover_stability ~ loreau_synchrony + shannon_mean*site*habitat, family = Gamma(link = "log"), data = diversity_stability, na.action = na.pass)
diversity_dredge <- dredge(diversity_mod_universal)
model.sel(diversity_dredge)

# top model is as follows (by a decent margin):
diversity_top <- glmmTMB(cover_stability ~ loreau_synchrony + shannon_mean*site + site*habitat, family = Gamma(link = "log"), data = diversity_stability, na.action = na.pass)
summary(diversity_top)
Anova(diversity_top)
```


```{r general cover diversity, fig.height = 30, fig.width = 30}
(diversity_cover_plot = 
  ggplot(data = alpha_diversity) +
  geom_point(aes(x = cover, y = shannon, colour = site, shape = habitat), size = 8, stroke = 2) + 
   scale_colour_manual(values = site_colours) +
   scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~year) +
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         ) # ABORT ABORT ABORT
```

```{r diversity stability quadrat level setup, fig.height = 20, fig.width=20}
data_sub$stratum <- as.factor(paste(data_sub$site, "-", data_sub$habitat, "-", data_sub$transect))
data_sub$location <- as.factor(data_sub$location)


quadrat_portfolio_columns <- c("location", "portfolio_effect") # names of columns for dataframe
quadrat_level_portfolio <- 
  data.frame(matrix(nrow = length(unique(data_sub$location)), 
                    ncol = length(quadrat_portfolio_columns))
             )
colnames(quadrat_level_portfolio) <- quadrat_portfolio_columns # change column 
quadrat_level_portfolio$location <- unique(data_sub$location) # populate

for(i in 1:length(unique(unique(data_sub$location))) ){ # for each  quadrat
  # create a new dataframe for current quadrat
  newData <- subset(data, location == levels(data_sub$location)[i])
  current_matrix <- newData[ , -which(names(newData) %in% meta_cols)] # remove metadata columns
  if(sum(current_matrix) == 0 | # if this was a 0 algae quadrat
     # or if there was only 1 column after removing all irrelevant algae
     is.null(ncol(current_matrix[, which(colSums(current_matrix) != 0)]))){ 
    quadrat_level_portfolio[i, 2] <- NA # set portfolio effects to 0
  }else{ # otherwise
    current_matrix <- current_matrix[, which(colSums(current_matrix) != 0)] # remove irrelevant algae
    
    quadrat_level_portfolio[i, 2] <- pe_mv(current_matrix, "loess_detrended") # calculate portfolio effects for current time series
  }
  
}

# sum(is.na(quadrat_level_portfolio$portfolio_effect)) # 4 quadrats causing trouble

hist(quadrat_level_portfolio$portfolio_effect) # some crazy outliers due to low richness

alpha_diversity_quad$cover <- rowSums(data[ , -which(names(data) %in% meta_cols)])/100
alpha_diversity_quad_sub <- alpha_diversity_quad[!alpha_diversity_quad$location %in% problem_children, ]

# alpha_diversity_quad_sub$cover <- rowSums(data_sub[ , -which(names(data_sub) %in% meta_cols)])/100
alpha_diversity_quad_sub$stratum <- 
  paste(alpha_diversity_quad_sub$site, "-", alpha_diversity_quad_sub$habitat, "-", alpha_diversity_quad_sub$transect)
lm_synchrony_quadrat <- codyn::synchrony(df = long_data_sub,
                                   time.var = "year",
                                   species.var = "taxa",
                                   abundance.var = "percent_cover",
                                   metric = "Loreau",
                                   replicate.var = "location") # Loreau and Mazancourt synchrony
colnames(lm_synchrony_quadrat) = c("location", "loreau_synchrony") # rename cols for merge later

## gross_synchrony_quadrat <- codyn::synchrony(df = long_data_sub,
##                                    time.var = "year",
##                                    species.var = "taxa",
##                                    abundance.var = "percent_cover",
##                                    metric = "Gross",
##                                    replicate.var = "location") # lots of warnings in this one - examine further later
## colnames(gross_synchrony_transect) = c("location", "Gross_synchrony") # rename cols for merge later

variance_ratio_quadrat <- variance_ratio(df = long_data_sub,
                                   time.var = "year",
                                   species.var = "taxa",
                                   abundance.var = "percent_cover",
                                   average.replicates = F,
                                   bootnumber = 1,
                                   replicate.var = "location")

community_stability_quadrat <- community_stability(df = long_data_sub,
                                   time.var = "year",
                                   abundance.var = "percent_cover",
                                   replicate.var = "location")
colnames(community_stability_quadrat) = c("location", "cover_stability")

diversity_stability_quadrat <- alpha_diversity_quad_sub %>%
  dplyr::group_by(location, site, habitat, island_side, site_habitat, transect, stratum) %>%
  dplyr::summarise(richness_mean = mean(richness), 
            richness_se = sd(richness)/sqrt(n()),
            richness_cv = CV(richness),
            shannon_mean = mean(shannon), 
            shannon_se = sd(shannon)/sqrt(n()),
            shannon_cv = CV(shannon),
            shannon_stability = 1/CV(shannon), # Stability as defined by codyn and many others (including Pete in 2022 paper)
            cover_mean = mean(cover),
            cover_se = sd(cover)/sqrt(n()),
            cover_cv = CV(cover)) 

diversity_stability_quadrat <- 
  merge(diversity_stability_quadrat, lm_synchrony_quadrat, by = "location") # add in loreau and de Mazancourt synchrony
# diversity_stability_quadrat <- merge(diversity_stability_quadrat, gross_synchrony_quadrat, by = "location")
diversity_stability_quadrat <- merge(diversity_stability_quadrat, quadrat_level_portfolio, by = "location") # add in portfolio effects
diversity_stability_quadrat <- merge(diversity_stability_quadrat, variance_ratio_quadrat, by = "location")
diversity_stability_quadrat <- merge(diversity_stability_quadrat, community_stability_quadrat, by = "location")
pairs(~ cover_mean + cover_cv + cover_stability + 
        shannon_mean + shannon_cv + shannon_stability + 
        loreau_synchrony +  portfolio_effect + VR, data = diversity_stability_quadrat)

```

```{r cover and cv, fig.height = 8, fig.width = 10}
(cover_cv_plot = 
  ggplot(data = diversity_stability_quadrat) +
  geom_point(aes(x = cover_mean, y = cover_cv, colour = site, shape = habitat), size = 4) + 
   scale_colour_manual(values = site_colours) +
  scale_shape_manual(values = habitat_shapes) +
   facet_wrap(~site) +

  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         )

(cover_cv_plot = 
  ggplot(data = diversity_stability_quadrat) +
  geom_point(aes(x = cover_mean, y = shannon_mean, colour = site, shape = habitat), size = 4) + 
   scale_colour_manual(values = site_colours) +
  scale_shape_manual(values = habitat_shapes) +
   facet_wrap(~site) +

  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         )

```

```{r basic diversity stability plots quadrat level, fig.height=8, fig.width=10}


richness_cv_mod <- glmmTMB(cover_cv ~ richness_mean*habitat*island_side + (1|site/transect), family = Gamma(link = "log"),
                          data = diversity_stability_quadrat, na.action = na.pass)
# model.sel(dredge(richness_cv_mod)) # top model is as specified, second best (delta = 10) doesn't include rich:hab:coast
r.squaredGLMM(richness_cv_mod) # 0.61, 0.64
summary(richness_cv_mod)
emmeans(richness_cv_mod, pairwise ~ island_side | habitat, var = "richness_mean")
richness_cv_emm <- emmip(richness_cv_mod,
                        habitat ~ richness_mean | island_side,
                        at = list(richness_mean = seq(0,5,0.1)), plotit = F, CIs = T)

(richness_cv_plot = 
  ggplot() +
  geom_point(data = diversity_stability_quadrat,
             aes(x = richness_mean, y = cover_cv, colour = island_side, shape = habitat), size = 2, alpha = 0.5) + 
  geom_line(data = richness_cv_emm, aes(x = richness_mean, y = exp(yvar), colour = island_side), size = 2) +
  geom_ribbon(data = richness_cv_emm, aes(x = richness_mean, ymin = exp(LCL), ymax = exp(UCL), fill = island_side), alpha = 0.3) +
#   scale_colour_manual(values = site_colours) +
  scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~habitat) +

  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         )

(shannon_cv_plot_2 = 
  ggplot(data = diversity_stability_quadrat) +
  geom_point(aes(x = shannon_mean, y = cover_cv, colour = site, shape = habitat), size = 4, stroke = 1) + 
   scale_colour_manual(values = site_colours) +
   scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~habitat) +
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         )

# lter_2 obscures a lot of the trends


```

```{r portfolio effects and synchrony transect level,  fig.height = 8, fig.width = 10}
synchrony_cv_mod <- glmmTMB(cover_cv ~ loreau_synchrony*habitat*island_side + (1|island_side/site/transect), 
                             family = Gamma(link = "log"),
                          data = diversity_stability_quadrat, na.action = na.pass)
# model.sel(dredge(synchrony_cv_mod)) # top model by far is as specified
r.squaredGLMM(synchrony_cv_mod) # 0.78, 0.79
summary(synchrony_cv_mod)
emmeans(synchrony_cv_mod, pairwise ~ island_side | habitat, var = "loreau_synchrony", at = list(loreau_synchrony = seq(0,1,0.05)))
synchrony_cv_emm <- emmip(synchrony_cv_mod,
                        habitat ~ loreau_synchrony | island_side,
                        at = list(loreau_synchrony = seq(0,1,0.05)), plotit = F, CIs = T)

(loreau_stability_plot_quad = 
  ggplot(data = diversity_stability_quadrat) +
  geom_point(aes(x = loreau_synchrony, y = cover_cv, colour = island_side, shape = habitat), size = 2, alpha = 0.5) + 
 # geom_line(data = synchrony_cv_emm, aes(x = loreau_synchrony, y = exp(yvar), colour = island_side), size = 1) +
 # geom_ribbon(data = synchrony_cv_emm, aes(x = loreau_synchrony, ymin = LCL, ymax = UCL, fill = island_side),
 #             alpha = 0.3) +
   scale_shape_manual(values = habitat_shapes) +
#  facet_wrap(~habitat) +
   
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         )

# (gross_stability_plot_quad = 
#   ggplot(data = diversity_stability_quadrat) +
#   geom_point(aes(x = Gross_synchrony, y = cover_stability, colour = site, shape = habitat), size = 8, stroke = 2) + 
#    scale_colour_manual(values = site_colours) +
#    scale_shape_manual(values = habitat_shapes) +
#   facet_wrap(~site) +
#    
#   theme_bw() + 
#   theme(axis.title.x = element_text(size=18), 
#         axis.title.y = element_text(size=18), 
#         panel.background = element_blank(), 
#         panel.grid.major = element_blank(),  #remove major-grid labels
#         panel.grid.minor = element_blank(),  #remove minor-grid labels
#         plot.background = element_blank(),
#         legend.text = element_text(size = rel(1)), # increase legend text
#         legend.title = element_text(size = rel(1)),
#         legend.position = 'bottom', # move legend to bottom
#         legend.box = 'horizontal', # make legend horizontal
#         legend.box.background = element_rect(colour = "black"))  # add box around legend
#          )

(portfolio_stability_plot_quad = 
  ggplot(data = diversity_stability_quadrat) +
  geom_point(aes(x = portfolio_effect, y = cover_cv, colour = site, shape = habitat), size = 4, stroke = 2) + 
   scale_colour_manual(values = site_colours) +
   scale_shape_manual(values = habitat_shapes) +
 # facet_wrap(~site) +
   
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         ) # almost a perfect line, which makes sense given that CV is a component of portfolio effects

```

```{r diversity portfolio effects and synchrony quadrat level,  fig.height = 8, fig.width = 10}
(loreau_diversity_plot_quad = 
  ggplot(data = diversity_stability_quadrat) +
  geom_point(aes(x = shannon_mean, y = loreau_synchrony, colour = site, shape = habitat), size = 4, stroke = 1) + 
   scale_colour_manual(values = site_colours) +
   scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~site) +
   
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         )



(portfolio_diversity_plot_quad = 
  ggplot(data = diversity_stability_quadrat) +
  geom_point(aes(x = shannon_mean, y = portfolio_effect, colour = site, shape = habitat), size = 4, stroke = 2) + 
   scale_colour_manual(values = site_colours) +
   scale_shape_manual(values = habitat_shapes) +
  facet_wrap(~site) +
   
  theme_bw() + 
  theme(axis.title.x = element_text(size=18), 
        axis.title.y = element_text(size=18), 
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank(),
        legend.text = element_text(size = rel(1)), # increase legend text
        legend.title = element_text(size = rel(1)),
        legend.position = 'bottom', # move legend to bottom
        legend.box = 'horizontal', # make legend horizontal
        legend.box.background = element_rect(colour = "black"))  # add box around legend
         )
```

```{r diversity models quad level}
diversity_mod_universal <- glmmTMB(cover_cv ~shannon_mean*site + shannon_mean*habitat + site*habitat + (1|transect/location), family = Gamma(link = "log"), data = diversity_stability_quadrat, na.action = na.pass)
diversity_dredge <- dredge(diversity_mod_universal)
model.sel(diversity_dredge) # best model is as specified
summary(diversity_mod_universal) # low variance in random effects
Anova(diversity_mod_universal) # LR Tests are kinda useless
r.squaredGLMM(diversity_mod_universal) # 0.653, 0.655

synchrony_mod_universal <- glmmTMB(cover_cv ~loreau_synchrony*site + loreau_synchrony*habitat + site*habitat + (1|transect/location), family = Gamma(link = "log"), data = diversity_stability_quadrat, na.action = na.pass)
synchrony_dredge <- dredge(synchrony_mod_universal)
model.sel(synchrony_dredge) # best model is as specified
summary(synchrony_mod_universal)
r.squaredGLMM(synchrony_mod_universal) # 0.800, 0.802

diversity_stability_quadrat$loreau_synchrony_trans <- sv_trans(diversity_stability_quadrat$loreau_synchrony, diversity_stability_quadrat) # for modelling on beta
synchrony_diversity_universal <- glmmTMB(loreau_synchrony_trans ~shannon_mean*site + shannon_mean*habitat + site*habitat + (1|transect/location), family = beta_family(), data = diversity_stability_quadrat, na.action = na.pass)
model.sel(dredge(synchrony_diversity_universal)) # best model as specified
summary(synchrony_diversity_universal)
Anova(synchrony_diversity_universal)
r.squaredGLMM(synchrony_diversity_universal) # Model's distribution-specific variance is negative. Results are not reliable.

```

```{r new csvs for joint analyses}
# write_csv(alpha_diversity_quad, here("data", "algae_diversity_quadrat.csv"))
# write_csv(diversity_stability_quadrat, here("data", "algae_diversity_stability_metrics_quadrat.csv"))

# algal diversity site level
diversity_site <- alpha_diversity_quad %>%
  dplyr::group_by(year, island_side, site, habitat, site_habitat) %>%
  dplyr::summarise(algae_cover_mean = mean(cover),
                   algae_cover_se = sd(cover)/sqrt(n()),
                   algae_richness_mean = mean(richness),
                   algae_shannon_mean = mean(shannon), 
                   algae_shannon_se = sd(shannon)/sqrt(n())
  )
# write_csv(diversity_site, here("data", "algae_diversity_site.csv"))

diversity_stability_quadrat <- alpha_diversity_quad_sub %>%
  dplyr::group_by(location, site, habitat, site_habitat, transect, stratum) %>%
  dplyr::summarise(richness_mean = mean(richness), 
            richness_se = sd(richness)/sqrt(n()),
            richness_cv = CV(richness),
            shannon_mean = mean(shannon), 
            shannon_se = sd(shannon)/sqrt(n()),
            shannon_cv = CV(shannon),
            shannon_stability = 1/CV(shannon), # Stability as defined by codyn and many others (including Pete in 2022 paper)
            cover_mean = mean(cover),
            cover_se = sd(cover)/sqrt(n()),
            cover_cv = CV(cover)) 
# create csv for site level
new_csv_meta <- c("year", "island_side", "site", "habitat", "site_habitat") # relevant metadata
cols_to_remove <- meta_cols[!meta_cols %in% new_csv_meta] # columns that don't overlap between metadata vectors
reduced_diversity_stability <- diversity_stability_quadrat[ , -which(names(diversity_stability_quadrat) %in% cols_to_remove)]

# averaging from the original here to avoid taking average of average, cv of cv, etc.
diversity_cv_site <- alpha_diversity_quad %>%
  dplyr::group_by(site, habitat, island_side, site_habitat) %>%
  dplyr::summarise(algae_richness_mean = mean(richness), 
            algae_richness_se = sd(richness)/sqrt(n()),
            algae_richness_cv = CV(richness),
            algae_shannon_mean = mean(shannon), 
            algae_shannon_se = sd(shannon)/sqrt(n()),
            algae_shannon_cv = CV(shannon),
            algae_shannon_stability = 1/CV(shannon), # Stability as defined by codyn and many others (including Pete in 2022 paper)
            algae_cover_mean = mean(cover),
            algae_cover_se = sd(cover)/sqrt(n()),
            algae_cover_cv = CV(cover)) 

# portfolio and synchrony need to be calculated at quad level, so taking the mean of the quad level for these
# synchrony_portfolio_site <- diversity_stability_quadrat %>%
#   dplyr::group_by(site, habitat, island_side, site_habitat) %>%
#   dplyr::summarise(
#             algae_loreau_mean = mean(loreau_synchrony),
#             algae_loreau_se = sd(loreau_synchrony)/sqrt(n()),
#             algae_portfolio_mean = mean(portfolio_effect),
#             algae_portfolio_se = sd(portfolio_effect)/sqrt(n()))
# NOT DOING IT LIKE THIS ANYMORE! DOING IT BY RECALCULATING SYNCHRONY WITH SITE AS REPLICATE
lm_synchrony_site <- codyn::synchrony(df = site_level,
                                   time.var = "year",
                                   species.var = "taxa",
                                   abundance.var = "mean_site_cover",
                                   metric = "Loreau",
                                   replicate.var = "site_habitat") # Loreau and Mazancourt synchrony
colnames(lm_synchrony_site) = c("site_habitat", "loreau_synchrony") # rename cols for merge later


wide_site_level <- data %>%
  dplyr::group_by(year, island_side, island_side_habitat, site, habitat, site_habitat) %>%
  dplyr::summarize(across(all_of(species_cols), mean, na.rm = TRUE))
wide_site_level$site_habitat <- as.factor(wide_site_level$site_habitat)

site_portfolio_columns <- c("site_habitat", "portfolio_effect") # names of columns for dataframe
site_level_portfolio <- 
  data.frame(matrix(nrow = length(unique(wide_site_level$site_habitat)), 
                    ncol = length(site_portfolio_columns))
             )
colnames(site_level_portfolio) <- site_portfolio_columns # change column 
site_level_portfolio$site_habitat <- unique(wide_site_level$site_habitat) # populate


for(i in 1:length(unique(wide_site_level$site_habitat)) ){ # for each  site
  # create a new dataframe for current site
  newData <- subset(wide_site_level, site_habitat == levels(wide_site_level$site_habitat)[i])
  current_matrix <- newData[ , -which(names(newData) %in% meta_cols)] # remove metadata columns
  if(sum(current_matrix) == 0){ # if this was a 0 algae site
    site_level_portfolio[i, 2] <- NA # set portfolio effects to 0
  }else{ # otherwise
    current_matrix <- current_matrix[, which(colSums(current_matrix) != 0)] # remove irrelevant algae
    
    site_level_portfolio[i, 2] <- pe_mv(current_matrix, "loess_detrended") # calculate portfolio effects for current time series
  }
  
}

# merge together
diversity_stability_site <- merge(diversity_cv_site, lm_synchrony_site, by = "site_habitat")
diversity_stability_site <- merge(diversity_stability_site, site_level_portfolio, by = "site_habitat")

# write_csv(diversity_stability_site, here("data", "algae_diversity_stability_metrics_site.csv"))

```


