---
title: "Richness model"
output: html_document
date: "2024-07-30"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# clean up
rm(list=ls()) 

# load packages
require(here) # relative file paths
require(tidyverse) # data wrangling
require(lme4) # mixed models

```

Make a model for algal richness through time

# Bring in the data

```{r load data}
cleaned_rich <- read_csv(here("data/algae_diversity_quadrat.csv")) %>% # generated using my (Julianna's) algal metric wrangling code
  filter(year != 2020) %>% # fake data
  # make a unique quadrat ID
  mutate(quad_id = paste0(transect, "_", quadrat))
  
```

# Full model no site

WARNING: This is reeeeeally slow code to run

```{r make Poisson model}
mRich <- glmer(algae_richness ~ as.factor(year)*habitat + (1|site/quad_id),
               family = poisson,
               data = cleaned_rich)
```

# Examine output

```{r make prediction grid}
# create a grid to predict over
newdata <- expand_grid(year = unique(cleaned_rich$year),
                       habitat = unique(cleaned_rich$habitat),
                       site = unique(cleaned_rich$site),
                       quad_id = unique(cleaned_rich$quad_id))
```

```{r generate predictions}
newdata$Preds <- predict(mRich, newdata = newdata, "response")
```

**IMPORTANT**: I don't think this is the correct way to get the error bars

```{r plot predictions}
newdata %>% 
  # get transect means
  group_by(year, habitat) %>% 
  summarize(Pred_mean_richness = mean(Preds),
            SD_richness = sd(Preds),
            N = n(),
            SE_richness = SD_richness/sqrt(N)
            ) %>% 
  ggplot(aes(x = year, y = Pred_mean_richness, group = habitat, color = habitat)) +
  geom_line() +
  theme_bw() +
  ylab("Predicted mean richness") +
  xlab("Year") +
  # add lines for disturbances
  geom_vline(xintercept = 2006, linetype = "dotdash") + # start of COTS
  geom_vline(xintercept = 2010,  color = "darkgray") + # cyclone Oli
  geom_vline(xintercept = 2019, linetype = "dashed", color = "red")  # bleaching

```

# Full model with site

```{r make Poisson model}
mRichSite <- glm(algae_richness ~ as.factor(year)*habitat*site,
               family = poisson,
               data = cleaned_rich) # optimizer when using glmer() was taken from : https://stackoverflow.com/questions/69929896/glmer-taking-days-to-compute-and-never-ending)
# not converging I'm not sure what's wrong? Maybe that's just like literally specifying everything? Took 1|quad_id out
```

# Examine output

```{r make prediction grid}
# create a grid to predict over
newdataSite <- expand_grid(year = unique(cleaned_rich$year),
                       habitat = unique(cleaned_rich$habitat),
                       site = unique(cleaned_rich$site),
                       quad_id = unique(cleaned_rich$quad_id))
```

```{r generate predictions}
newdataSite$Preds <- predict(mRichSite, newdata = newdataSite, "response")
```

```{r plot predictions}
newdataSite %>% 
  # get transect means
  group_by(year, habitat, site) %>% 
  summarize(Pred_mean_richness = mean(Preds),
            SD_richness = sd(Preds),
            N = n(),
            SE_richness = SD_richness/sqrt(N)
            ) %>% 
  ggplot(aes(x = year, y = Pred_mean_richness, group = habitat)) +
  geom_line(aes(color = site, group = site)) +
  theme_bw() +
  facet_wrap(~habitat) +
  # add lines for disturbances
  geom_vline(xintercept = 2006, linetype = "dotdash") + # start of COTS
  geom_vline(xintercept = 2010,  color = "darkgray") + # cyclone Oli
  geom_vline(xintercept = 2019, linetype = "dashed", color = "red")  # bleaching

```
